version: "3"

networks:
  laravel:

services:
  site:
    build:
      context: ./dockerfiles
      dockerfile: nginx.root.dockerfile
    ports:
      - 8089:80
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - pgsql
      #- redis
    networks:
      - laravel

  pgsql:
    image: postgres:14-alpine3.15
    ports:
      - 5439:5432
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ocana
      POSTGRES_PASSWORD: ocana
      SERVICE_TAGS: dev
      SERVICE_NAME: pgsql
    volumes:
      - ./pgsql:/var/lib/postgresql/data
    networks:
      - laravel

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.root.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    networks:
      - laravel

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "${FORWARD_MEILISEARCH_PORT:-7700}:7700"
    volumes:
      - ./meilisearch:/data.ms
    networks:
      - laravel

  composer:
    image: composer:2
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: root
    entrypoint: ["composer", "--ignore-platform-reqs"]
    networks:
      - laravel

  npm:
    image: node:13.7
    volumes:
      - ./src:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - laravel

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.root.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - pgsql
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - laravel
